name: Deploy to Github Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Update Hugo Modules
        run: hugo mod tidy

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install node modules
        run: |
          hugo mod npm pack
          npm install

      - name: Build to /docs
        run: hugo --minify --destination docs

      - name: Debug docs contents
        run: |
          echo "Built files:"
          find docs -type f || echo "Nothing built. Check hugo build output."
          ls -lah docs || true

      - name: Fail if docs is empty
        run: |
          if [ -z "$(ls -A docs)" ]; then
            echo "docs/ is empty. Build likely failed."
            exit 1
          fi

      - name: Commit built docs to main
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "Deploy updated docs"
          git push